name: file_sharing_backend
description: Dart backend server for smart file sharing application.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '^3.10.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.4
  sqlite3: ^2.1.0
  dotenv: ^4.2.0
  uuid: ^4.0.0
  dart_jsonwebtoken: ^2.10.2
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
